
services:
  db:
    networks:
      - proxy
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    networks:
      - proxy
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"

  app:
    build: .
    networks:
      - proxy
    ports:
      - "8080:80"
    volumes:
      - ../ksp:/var/www/
    depends_on:
      - db

volumes:
  db-data:

networks:
  proxy:
    external: true
