# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: 'Europe/Paris'
    app_url: '%env(APP_URL)%'
    app.cleanup_cron: '0 2 * * *' # Every day at 2:00 AM

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\EventListener\JWTCreatedListener:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_jwt_created', method: 'onJWTCreated' }

    App\EventListener\UserActivityListener:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Service\SendingEmail\SendResetPasswordEmailService:
        arguments:
            $baseUrl: '%app_url%'  # Injecter le paramètre app_url

    App\Service\SendingEmail\SendUpdateCoursEmailService:
        arguments:
            $baseUrl: '%app_url%'  # Injecter le paramètre app_url
            
    App\Service\SendingEmail\SendDesistementEmailService:
        arguments:
            $baseUrl: '%app_url%'
            
    App\Service\SendingEmail\SendToUsersCoursAvailabilityService:
        arguments:
            $baseUrl: '%app_url%'
            
    App\Scheduler\ScheduleProvider:
        arguments:
            $cronExpression: '%app.cleanup_cron%' # Injecter le paramètre app.cleanup_cron

    App\Controller\Api\AuthController:
        arguments:
            $forgotPasswordLimiter: '@limiter.forgot_password_limiter'
            $resetPasswordLimiter: '@limiter.reset_password_limiter'

    Stripe\StripeClient:
        arguments:
            - { api_key: '%env(STRIPE_PRIVATE_KEY)%' }
    
    _instanceof:
        App\Service\Interface\Notification\NotificationSenderInterface:
            tags: [ 'app.notification_sender' ]
            
    App\Service\Notification\EmailSender:
        arguments:
            $fromEmail: '%env(MAILER_SENDER)%'  
            
